// Shared demo data for timeline-like components
// Used by TimelineFeed and TimelinePreview to ensure consistency

export const posts = [
  {
    id: 1,
    type: 'clinic_update',
    clinic: {
      name: 'Anadolu Sağlık Merkezi',
      location: 'İstanbul',
      avatar: 'https://placehold.co/40x40',
      verified: true,
      specialty: 'Kalp Cerrahisi',
    },
    timestamp: '2 saat önce',
    content:
      "🔬 Yeni teknoloji ile minimal invaziv kalp ameliyatlarımızda başarı oranımız %98'e ulaştı! Hastalarımızın iyileşme süreleri yarıya indi.",
    hashtags: ['#KalpCerrahisi', '#MinimalInvaziv'],
    image: 'https://placehold.co/600x300',
    engagement: {
      likes: 124,
      comments: 18,
      shares: 12,
    },
    hasAppointmentButton: true,
  },
  {
    id: 2,
    type: 'patient_review',
    patient: {
      name: 'Mehmet Kaya',
      avatar: 'https://placehold.co/40x40',
      isPatient: true,
    },
    timestamp: '4 saat önce',
    rating: 5,
    content:
      "Memorial Hastanesi'nde estetik operasyonum çok başarılı geçti! Dr. Ahmet Yılmaz ve ekibine çok teşekkür ederim. Hem öncesi hem sonrası süreçte çok ilgili davrandılar. Kesinlikle tavsiye ederim! 🔬",
    verificationBadge: {
      text: 'Onaylanmış Değerlendirme',
      description:
        'Bu değerlendirme sistem üzerinden randevu alan gerçek bir hasta tarafından yapılmıştır.',
    },
    engagement: {
      likes: 89,
      comments: 12,
      shares: 5,
    },
  },
  {
    id: 3,
    type: 'clinic_update',
    clinic: {
      name: 'Medicana International',
      location: 'Ankara',
      avatar: 'https://placehold.co/40x40',
      verified: true,
      specialty: 'Onkoloji',
    },
    timestamp: '6 saat önce',
    content:
      'Yeni immünoterapi protokolümüz ile yan etki oranlarını %30 azalttık, tedavi uyumunu artırdık.',
    hashtags: ['#Onkoloji', '#İmmünoterapi'],
    image: 'https://placehold.co/640x320',
    engagement: {
      likes: 76,
      comments: 9,
      shares: 7,
    },
  },
  {
    id: 4,
    type: 'patient_review',
    patient: {
      name: 'Ayşe Demir',
      avatar: 'https://placehold.co/40x40',
      isPatient: true,
    },
    timestamp: '8 saat önce',
    rating: 4,
    content:
      'Göz lazer operasyonum sorunsuz geçti. Klinik çok temiz ve ekip çok ilgiliydi. Sadece kontrol randevusu için yoğunluk vardı.',
    engagement: {
      likes: 42,
      comments: 6,
      shares: 2,
    },
  },
  {
    id: 5,
    type: 'clinic_update',
    clinic: {
      name: 'Memorial Şişli',
      location: 'İstanbul',
      avatar: 'https://placehold.co/40x40',
      verified: false,
      specialty: 'Ortopedi',
    },
    timestamp: '12 saat önce',
    content:
      'Robotik diz protezi ameliyatlarımızda ameliyat sürelerini kısalttık, rehabilitasyon daha hızlı ilerliyor.',
    hashtags: ['#Ortopedi', '#RobotikCerrahi'],
    image: 'https://placehold.co/560x280',
    engagement: {
      likes: 63,
      comments: 11,
      shares: 3,
    },
  },
  {
    id: 6,
    type: 'patient_review',
    patient: {
      name: 'Can Yılmaz',
      avatar: 'https://placehold.co/40x40',
      isPatient: true,
    },
    timestamp: '14 saat önce',
    rating: 5,
    content:
      'Diş beyazlatma hizmetinden çok memnun kaldım. İşlem hızlı ve ağrısızdı, sonuçlar harika! Klinik personeli güler yüzlüydü.',
    engagement: {
      likes: 37,
      comments: 4,
      shares: 1,
    },
  },
  {
    id: 7,
    type: 'clinic_update',
    clinic: {
      name: 'Florence Nightingale',
      location: 'İstanbul',
      avatar: 'https://placehold.co/40x40',
      verified: true,
      specialty: 'Nöroloji',
    },
    timestamp: '16 saat önce',
    content: 'Yeni MR cihazımız ile görüntü kalitesi %25 arttı, randevu süreleri kısaldı.',
    hashtags: ['#Nöroloji', '#Görüntüleme'],
    image: 'https://placehold.co/600x300',
    engagement: { likes: 58, comments: 7, shares: 3 },
  },
  {
    id: 8,
    type: 'patient_review',
    patient: { name: 'Elif Öz', avatar: 'https://placehold.co/40x40', isPatient: true },
    timestamp: '18 saat önce',
    rating: 5,
    content: 'Diyetisyen danışmanlığıyla 3 ayda sağlıklı şekilde 8 kilo verdim. Çok teşekkürler!',
    engagement: { likes: 41, comments: 5, shares: 1 },
  },
  {
    id: 9,
    type: 'clinic_update',
    clinic: { name: 'Acıbadem Maslak', location: 'İstanbul', avatar: 'https://placehold.co/40x40', verified: true, specialty: 'Kardiyoloji' },
    timestamp: '1 gün önce',
    content: 'Kalp ritim bozukluklarında yeni ablasyon tekniği ile başarı oranı %96.',
    hashtags: ['#Kardiyoloji'],
    image: 'https://placehold.co/640x320',
    engagement: { likes: 73, comments: 10, shares: 6 },
  },
  {
    id: 10,
    type: 'patient_review',
    patient: { name: 'Burak Çetin', avatar: 'https://placehold.co/40x40', isPatient: true },
    timestamp: '1 gün önce',
    rating: 4,
    content: 'Fizik tedavi sürecim verimli geçti. Randevu saatlerinde bazen gecikme yaşandı.',
    engagement: { likes: 22, comments: 3, shares: 0 },
  },
  {
    id: 11,
    type: 'clinic_update',
    clinic: { name: 'Başkent Üniversitesi', location: 'Ankara', avatar: 'https://placehold.co/40x40', verified: false, specialty: 'Genel Cerrahi' },
    timestamp: '1 gün önce',
    content: 'Günübirlik cerrahi ile taburculuk süreleri kısaldı.',
    hashtags: ['#GenelCerrahi'],
    image: 'https://placehold.co/560x280',
    engagement: { likes: 31, comments: 2, shares: 1 },
  },
  {
    id: 12,
    type: 'patient_review',
    patient: { name: 'Selin A.', avatar: 'https://placehold.co/40x40', isPatient: true },
    timestamp: '1 gün önce',
    rating: 5,
    content: 'Lazer epilasyon hizmetinde hijyen ve konfor çok iyiydi, sonuçlardan memnunum.',
    engagement: { likes: 48, comments: 6, shares: 2 },
  },
  {
    id: 13,
    type: 'clinic_update',
    clinic: { name: 'Medipol Mega', location: 'İstanbul', avatar: 'https://placehold.co/40x40', verified: true, specialty: 'Ortopedi' },
    timestamp: '2 gün önce',
    content: 'Sporcu sağlığında yeni rehabilitasyon programı devrede.',
    hashtags: ['#Ortopedi', '#SporcuSağlığı'],
    image: 'https://placehold.co/600x300',
    engagement: { likes: 29, comments: 4, shares: 1 },
  },
  {
    id: 14,
    type: 'patient_review',
    patient: { name: 'Gizem T.', avatar: 'https://placehold.co/40x40', isPatient: true },
    timestamp: '2 gün önce',
    rating: 5,
    content: 'Doğum deneyimim çok güzel geçti, tüm ekibe minnettarım.',
    engagement: { likes: 65, comments: 9, shares: 4 },
  },
  {
    id: 15,
    type: 'clinic_update',
    clinic: { name: 'Ekol Hastanesi', location: 'İzmir', avatar: 'https://placehold.co/40x40', verified: false, specialty: 'KBB' },
    timestamp: '2 gün önce',
    content: 'Geniz eti ameliyatlarında çocuklar için ağrısız yöntemler benimsendi.',
    hashtags: ['#KBB'],
    image: 'https://placehold.co/560x280',
    engagement: { likes: 19, comments: 2, shares: 0 },
  },
  {
    id: 16,
    type: 'patient_review',
    patient: { name: 'Alper S.', avatar: 'https://placehold.co/40x40', isPatient: true },
    timestamp: '3 gün önce',
    rating: 4,
    content: 'Göz muayenemde detaylı açıklamalar yapıldı, süreçten memnun kaldım.',
    engagement: { likes: 27, comments: 3, shares: 1 },
  },
  {
    id: 17,
    type: 'clinic_update',
    clinic: { name: 'Dokuz Eylül', location: 'İzmir', avatar: 'https://placehold.co/40x40', verified: true, specialty: 'Radyoloji' },
    timestamp: '3 gün önce',
    content: 'Radyasyon dozunu azaltan yeni protokol devreye alındı.',
    hashtags: ['#Radyoloji'],
    image: 'https://placehold.co/640x320',
    engagement: { likes: 44, comments: 6, shares: 2 },
  },
  {
    id: 18,
    type: 'patient_review',
    patient: { name: 'Zeynep A.', avatar: 'https://placehold.co/40x40', isPatient: true },
    timestamp: '3 gün önce',
    rating: 5,
    content: 'Ortodonti tedavimde görünmez plaklar çok konforlu oldu.',
    engagement: { likes: 33, comments: 5, shares: 1 },
  },
  {
    id: 19,
    type: 'clinic_update',
    clinic: { name: 'Yeditepe', location: 'İstanbul', avatar: 'https://placehold.co/40x40', verified: true, specialty: 'Dahiliye' },
    timestamp: '4 gün önce',
    content: 'Check-up paketlerinde kapsam genişletildi, uygun fiyatlar.',
    hashtags: ['#Dahiliye', '#Checkup'],
    image: 'https://placehold.co/600x300',
    engagement: { likes: 21, comments: 2, shares: 1 },
  },
  {
    id: 20,
    type: 'patient_review',
    patient: { name: 'Deniz K.', avatar: 'https://placehold.co/40x40', isPatient: true },
    timestamp: '4 gün önce',
    rating: 5,
    content: 'Diş implant sürecim ağrısız ve hızlı geçti. Tavsiye ederim.',
    engagement: { likes: 39, comments: 6, shares: 2 },
  },
];

export const professionalReview = {
  id: 'pro-review-1',
  reviewer: {
    name: 'MediTravel Profesyonel Değerlendirme',
    team: 'Uzman Ekip',
    badge: 'PRO Review',
    avatar: 'https://placehold.co/40x40',
  },
  timestamp: '1 gün önce',
  clinic: 'Ege Üniversitesi Tıp Fakültesi Profesyonel İnceleme',
  content:
    "Uzman ekibimiz Ege Üniversitesi Tıp Fakültesi'ni detaylı olarak inceledi. Akademik kadro, teknolojik altyapı ve hasta memnuniyeti açısından değerlendirmemiz...",
  images: ['https://placehold.co/150x100', 'https://placehold.co/150x100', 'https://placehold.co/150x100'],
  scores: {
    technology: 9.2,
    cleanliness: 9.5,
    staff: 9.2,
  },
  engagement: {
    likes: 156,
    comments: 24,
  },
};
